### ISSUE TITLE
history scroll

### ISSUE THREAD

**Issue by Gene-Dana** [magnatronus/oscilloscope#3]
HI there ! 

Out of everything I've seen, this is the simplest and clearest implementation of an oscilloscope library in Flutter ! I'm really impressed out how clear and easy it is ! 

What would you suggest if you wanted to to scroll through the datapoints, see the history?

**Comment by magnatronus** [comment]
@Gene-Dana interesting question, not sure - at the moment, but maybe you would need to actually record the data as it came in and then plot from the recording rather than 'live'. That way it may be possible to slip the display through the recording (i.e. to pan it back over the historical data)
